### PR TITLE
Fix a few missing text domains.

### PR DESCRIPTION
**Pull request by Camwyn**
https://d.pr/i/sZwK6V

The other items in the ticket all translated as expected.

[TEC-3908]

[TEC-3908]: https://theeventscalendar.atlassian.net/browse/TEC-3908

### CODE REVIEW

**Review by stratease — DISMISSED** [review]

**Review by borkweb — COMMENTED** [review]
Does this need a changelog entry or is it building off of another PR?

**Comment by Camwyn** [comment]
> Does this need a changelog entry or is it building off of another PR?

I thought it was going to be, but nope - added changelog.

**Review by stratease — APPROVED** [review]
Gorgeous.

**Comment by Camwyn** [comment]
had to fix some test - that dismisses reviews, sorry!

**Pull request merged**
