### PR TITLE
Make sure we have a link to Settings page on the Update page

### PR DESCRIPTION
**Pull request by bordoni**
📷  http://i.bordoni.me/v1Hk1wk44MPAJQI7X0LL

### CODE REVIEW

**Review by borkweb — APPROVED** [review]
🌵 💨

**Comment by borkweb** [comment]
Hrm. eslint is failing.

**Comment by borkweb** [comment]
Are the eslint issues with `src/resources/js/tec-update-6.0.0-notice.js` and `src/resources/js/custom-tables-v1/ct1-upgrade.js` something that'd cause those files to not package appropriately?

If not, we should definitely plan to fix those post 6.0.

**Comment by bordoni** [comment]
Nothing related to this I think @borkweb so I would fix Post v6

**Review by stratease — APPROVED** [review]

**Pull request merged**
