### PR TITLE
Wrong rel value causing HTML 5 and WCAG 2.1 compliance error [TEC-4129]

### PR DESCRIPTION
**Pull request by EugeneKyale**
This PR adds a valid rel value to the link tag for TEC REST API support in order to improve HTML 5 and WCAG 2.1 compliance.

Ticket : https://theeventscalendar.atlassian.net/browse/TEC-4129
Artifacts : 
Before Fix;
image
After Fix; 
image

### CODE REVIEW

**Comment by EugeneKyale** [comment]
> This PR adds a valid rel value to the link tag for TEC REST API support in order to improve HTML 5 and WCAG 2.1 compliance.
> 
> Ticket : https://theeventscalendar.atlassian.net/browse/TEC-4129 Artifacts : Before Fix; image After Fix; image

@lucatume as a precaution please take a look at this modification to determine whether there may be any unwanted trickle down effects. You seem to have added that URL intentionally so I don't want to miss anything.

**Review by jesseeproductions — APPROVED** [review]
The change looks good and tests are passing. I am approving, but good to hear if Luca has any comments before merging.

**Comment by EugeneKyale** [comment]
> The change looks good and tests are passing. I am approving, but good to hear if Luca has any comments before merging.

Great, thanks @jesseeproductions I'll wait to hear from Luca before merging.

**Review by lucatume — APPROVED** [review]
Reading a bit the code and the [`rel` attribute definition](https://www.w3schools.com/tags/att_link_rel.asp), I'd say the change is correct. My suspect is the original value was just a forgotten placeholder.

**Pull request merged**
