### PR TITLE
Reduce final package size

### PR DESCRIPTION
**Pull request by bordoni**
🎟 [TCMN-42]
---
We are receiving a lot of customers complains where The Events Calendar is failing when updating to version 5.0.2+ which normally means that our package size is too big for the PHP to unzip on certain hosts. The problem isn't on downloading since we are below the normal failing point of `16MB`, it's the unzipped size that needs to be reduced the most.

The goal of the change is to reduce the file size which currently sits at:
- Unzipped: `36,557,757 bytes` or `~36.5MB`
- Zipped: `10,993,310 bytes` or `~10.9MB`

Currently, the changes I am pushing for here a will get us to the following file sizes:
- Unzipped: `22,217,660 bytes` or `~22.2MB`
- Zipped: `7,327,660 bytes` or `~7.3MB`

Depends on: https://github.com/moderntribe/tribe-common/pull/1309

**Files:**
- Old: [the-events-calendar.5.0.2.zip](https://github.com/moderntribe/the-events-calendar/files/4265052/the-events-calendar.5.0.2.zip)
- New: [the-events-calendar.5.0.3.zip](https://github.com/moderntribe/the-events-calendar/files/4265053/the-events-calendar.5.0.3.zip)

[TCMN-42]: https://moderntribe.atlassian.net/browse/TCMN-42

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Looks pretty good!

**Review by sc0ttkclark — DISMISSED** [review]
Looks like a great way to reduce file size, I'm on board!

**Comment by lucatume** [comment]
I've restarted the build as it seems it did time out.

**Comment by lucatume** [comment]
@bordoni some REST API tests are still failing, I've re-started the build and will check to see if this solves the issue.

**Pull request merged**
