### PR TITLE
[TEC-3944] Add not found message on day view mobile. 

### PR DESCRIPTION
**Pull request by EugeneKyale**
This PR ensures the day view on mobile displays the `not found` message when no events are present.

Ticket : https://theeventscalendar.atlassian.net/browse/TEC-3944
Artifact : https://www.loom.com/share/0d3d22030ce3426288a6c4f009bc299d

### CODE REVIEW

**Comment by paulmskim** [comment]
@EugeneKyale in your screencast, in mobile list view, the no events found message is above the top bar and datepicker. However, in the mobile day view, the no events found message is below the top bar and date picker. Is this on purpose, or do we want to make it consistent?

**Comment by EugeneKyale** [comment]
@paulmskim I added the notice below the date intentionally as per the instructions in the ticket. I'm also currently working to fix the tests.

**Comment by EugeneKyale** [comment]
@paulmskim I'm not sure why the tests are failing now. I've regenerated them successfully and all the tests are passing locally. Do you have any idea why this could be happening? 
image

**Comment by Camwyn** [comment]
> @paulmskim I'm not sure why the tests are failing now. I've regenerated them successfully and all the tests are passing locally. Do you have any idea why this could be happening? 

Looks like an issue with pretty permalinks?

**Comment by EugeneKyale** [comment]
@Camwyn It seems so, do we have a standard solution for this?

**Review by Camwyn — APPROVED** [review]

**Pull request merged**
