### PR TITLE
Feature/tec 3276 v2 map pin 2

### PR DESCRIPTION
**Pull request by jesseeproductions**
_Ref:_ [TEC-3276](https://theeventscalendar.atlassian.net/browse/TEC-3276)

Customizer setting: https://cloudup.com/iufgrSmQ-3T

Changes the Map V2 View and Single View. 

Venue V2 does not change and looks to require a change from using an iFrame to display the map. 

Map View: https://cloudup.com/iWv97Z-x_87
Single View: https://cloudup.com/iPkGYxZJdOr
Venue ( does not show ): https://cloudup.com/iTS8p4_Jrv1
https://developers.google.com/maps/documentation/embed/get-started#optional_parameters

Related PR: https://github.com/moderntribe/events-pro/pull/1641

### CODE REVIEW

**Review by paulmskim — COMMENTED** [review]
The PR should be based off of https://github.com/moderntribe/the-events-calendar/pull/3375, as there were many changes made to the customizer. However, this setting should only be set up in PRO, not in TEC, so that makes this PR moot. Let's move this work to PRO instead.

**Comment by jesseeproductions** [comment]
Closing per the last comment

**Review by lucatume — CHANGES_REQUESTED** [review]
From the code point of view, all fine.
Please, update the code with Paul's comment.

**Comment by jesseeproductions** [comment]
Hi @paulmskim,

I confirmed in the ticket that both TEC and Pro use this feature. 

https://theeventscalendar.atlassian.net/browse/TEC-3276?focusedCommentId=94345

For TEC it is the single events. 

So I believe this PR is still relevant as TEC should have the option as you can change single events without Pro. 

For Pro the change is for the Map View and the Pro PR handles that. 

Does that make sense?

**Comment by paulmskim** [comment]
@jesseeproductions gotcha, I hadn't thought about the event single. If we're allowing Google Maps API to be set in TEC, then this looks good.

**Comment by jesseeproductions** [comment]
@lucatume Please take another look. I believe this is set.

**Pull request merged**
